server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
#            - After=2020-04-15T17:42:02.866+08:00[Asia/Shanghai]
#            - Before=2020-04-15T15:42:02.866+08:00[Asia/Shanghai]
#            - Between=2020-04-15T16:42:02.866+08:00[Asia/Shanghai],2020-04-15T17:42:02.866+08:00[Asia/Shanghai]
#            - Cookie=username,wangliu
#            - Header=X-Request-Id,\d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username,\d+ #要有参数名username并且值还有是整数的才能路由

eureka:
  client: #客户端注册进eureka服务列表内
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
  instance:
    hostname: cloud-gateway-service
